{% set name = "xonsh" %}
{% set version = "0.9.22" %}
{% set sha256 = "cd2359fc05517b448e196fabafa177d78e6512e99e770c3d6a4304118701d2ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]
  entry_points:
    - xonsh = xonsh.main:main
    - xonsh-cat = xonsh.xoreutils.cat:cat_main
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - jupyter_client
  run:
    - python
    - prompt_toolkit
    - pygments >=2.2
    - pyreadline  # [win]
    - setproctitle

test:
  requires:
    - pytest
  imports:
    - xonsh
  commands:
    - USER=test xonsh -h  # [unix]
    - xonsh -h  # [win]

about:
  home: http://xon.sh
  license: BSD-2-Clause
  license_file: license
  summary: Python-powered, cross-platform, Unix-gazing shell
  description: |
    Xonsh is a Python-powered, cross-platform, Unix-gazing shell shell language
    and command prompt. The language is a superset of Python 3.4+ with
    additional shell primitives that you are used to from Bash and IPython. It
    works on all major systems including Linux, Mac OSX, and Windows. Xonsh is
    meant for the daily use of experts and novices alike.
  doc_url: http://xon.sh
  dev_url: https://github.com/xonsh/xonsh
